# Generated by Django 4.1.7 on 2023-05-09 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle_selection', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='displaycar',
            name='distributorinventory',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='displaycar',
            name='storeinventory',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='selectedcar',
            name='distributorinventory',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='selectedcar',
            name='storeinventory',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
