# Generated by Django 4.1.7 on 2023-05-09 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle_selection', '0003_rename_inventorystatus_newcarstock_dealercode_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usedcarstocks',
            old_name='dealerinventory',
            new_name='dealercode',
        ),
        migrations.AddField(
            model_name='usedcarstocks',
            name='distributorinventory',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='usedcarstocks',
            name='otherdealerinventory',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='usedcarstocks',
            name='stockinventory',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
